apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-db
    {{- include "micro-task-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres-db
    {{- include "micro-task-chart.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-db
    {{- include "micro-task-chart.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres-db
    {{- include "micro-task-chart.selectorLabels" . | nindent 4 }}