apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "micro-task-chart.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "micro-task-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "micro-task-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "micro-task-chart.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 3000  # frontend
    - protocol: TCP
      port: 8000  # backend
    - protocol: TCP
      port: 5432  # database
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "micro-task-chart.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 3000  # frontend
    - protocol: TCP
      port: 8000  # backend
    - protocol: TCP
      port: 5432  # database
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53