apiVersion: v1
kind: Secret
metadata:
  name: {{ include "micro-task-chart.fullname" . }}-backend-secrets
  labels:
    {{- include "micro-task-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  database-url: {{ .Values.backend.env.DATABASE_URL | b64enc | quote }}
  auth-secret: {{ .Values.backend.env.BETTER_AUTH_SECRET | b64enc | quote }}