{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "micro-task-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "micro-task-chart.labels" . | nindent 4 }}
type: Opaque
data:
  db-user: {{ .Values.database.postgresUser | b64enc | quote }}
  db-password: {{ .Values.database.postgresPassword | default "postgres" | b64enc | quote }}
  gemini-api-key: {{ .Values.backend.env.GEMINI_API_KEY | default (randAlphaNum 32) | b64enc | quote }}
  tracing-key: {{ .Values.backend.env.TRACING_KEY | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "micro-task-chart.fullname" . }}-backend-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "micro-task-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  auth-secret: {{ .Values.backend.env.BETTER_AUTH_SECRET | b64enc | quote }}